### ISSUE TITLE
libmongoc now splits out libbson

### ISSUE THREAD

**Issue by FeepingCreature** [2night/mondo#15]
dub.json should be

```
	"libs": [
		"mongoc-1.0",
		"bson-1.0"
	],
```

**Comment by trikko** [comment]
But the library is using a specific (old) commit of libmongo-c as you can see on main tree.

**Comment by FeepingCreature** [comment]
Oh I see. Is there a reason for that? I'm using a buildsystem that just translates the libs section into `-l` flags and using the system `libmongoc-1.0.a`, and it seems to be working.

**Comment by trikko** [comment]
Because they change the api/abi and I want to be sure I'm binding the right version. And mongo is (was?) not-so-well updated on main distros. 

Anyway if you want:
- Clone this
- Update the reference to a newer mongo version
- Try build libmongo (and libbson? I use `--with-libbson=bundled` to avoid having two libraries to bind)
- Run unittests!

**Comment by FeepingCreature** [comment]
I see I see. So it's fine then. My current plan: I'll stick with system lib, hold off on filing bugs for issues until I've reproed with the included lib, and not worry in the meantime.
